name: deployment workflow
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Compile Project
        run: |
          javac -cp "Projects/P2/src/" Projects/P2/src/*.java
          javac -cp "Projects/P2/tests/junit-4.10.jar:src/:tests/" Projects/P2/src/*.java Projects/P2/tests/*.java
  test_pacman_consume:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test pacman_consume
        run: |
          javac -cp "Projects/P2/src/" Projects/P2/src/*.java
          javac -cp "Projects/P2/tests/junit-4.10.jar:Projects/P2/src/:tests/" Projects/P2/src/*.java Projects/P2/tests/*.java
          java -cp "Projects/P2/tests/junit-4.10.jar:Projects/P2/src/:tests/" org.junit.runner.JUnitCore Projects/P2/tests/TestConsume
  test_ghost_attack:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test ghost_attack
        run: |
          javac -cp "Projects/P2/src/" Projects/P2/src/*.java
          javac -cp "Projects/P2/tests/junit-4.10.jar:Projects/P2/src/:tests/" Projects/P2/src/*.java Projects/P2/tests/*.java
          java -cp "Projects/P2/tests/junit-4.10.jar:Projects/P2/src/:tests/" org.junit.runner.JUnitCore Projects/P2/tests/TestAttack
  test_map_move:
    runs-on: ubuntu-latest
    container: openjdk
    steps:
      - uses: actions/checkout@v2
      - name: Test map_move
        run: |
          javac -cp "Projects/P2/src/" Projects/P2/src/*.java
          javac -cp "Projects/P2/tests/junit-4.10.jar:Projects/P2/src/:tests/" Projects/P2/src/*.java Projects/P2/tests/*.java
          java -cp "Projects/P2/tests/junit-4.10.jar:Projects/P2/src/:tests/" org.junit.runner.JUnitCore Projects/P2/tests/TestMapMove